---
- name: Set authorized keys
  become: false
  ansible.posix.authorized_key:
    user: "{{ ansible_user }}"
    state: present
    key: "{{ accessibility_keys_url }}"
  when: accessibility_keys_url is defined and accessibility_keys_url != ""

- name: Make sure we have a 'wheel' group
  ansible.builtin.group:
    name: wheel
    state: present
  when: accessibility_sudo_without_password

- name: Allow 'wheel' group to have passwordless sudo
  ansible.builtin.lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^%wheel'
    line: '%wheel ALL=(ALL) NOPASSWD: ALL'
    validate: 'visudo -cf %s'
  when: accessibility_sudo_without_password

- name: Add sudoers users to wheel group
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    groups:
      - wheel
    append: true
    state: present
    createhome: true
  when: accessibility_sudo_without_password
